### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by cthtrifork** [opensearch-project/opensearch-benchmark#347]
**Is your feature request related to a problem? Please describe.**

Our security model only allows OAuth2 authentication. See snippet:

```yaml
openid_auth_domain:
        order: 1
        description: "Authenticate via OIDC"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: openid
          challenge: false # JWT tokens already contain all required information, so challenge is unnecessary
          config:
            subject_key: osuser
            roles_key: osroles
            openid_connect_url: "${OIDC_ENDPOINT}"
```

But we have had to support basic auth + create a user to support this benchmark tool. The server admins are not happy about this.

**Describe the solution you'd like**

Support for token endpoint, client id and secret in the `generate-test` command instead of basic auth.

**Describe alternatives you've considered**

Alternatively we can get the token elsewhere (manually) and just supply it as an argument. 
The tokens expire after an hour and our tests takes a few minutes.
You would only need to take the suppied arguement and create a `Authorization`header  with the supplied value

**Additional context**
